# -*- coding: utf-8 -*-
"""GPS_REACTIONS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_mb3qBOt_qIVJREPV_exMLFMriA-LtdF
"""

################ NEW WORKOUT #################

import pandas as pd
import numpy as np

case_report= pd.read_excel('C:/Users/mkaya/Downloads/Genel Vaka Araştırma Raporu_20240806160405406.xls')

move_report= pd.read_excel('C:/Users/mkaya/Downloads/Report_istanbulsaglikrapor_Kontak Bazlı Araç Çalışma Raporu_06.08.2024_3fl1c352.1di.xlsx')

move_report['Başlangıç Tarihi']= move_report['Başlangıç Tarihi'].str.replace(' Ağustos ', '-08-').str.replace(' Pazartesi', '').str.replace(' Salı', '').str.replace(' Çarşamba', '').str.replace(' Perşembe', '').str.replace(' Cuma', '').str.replace(' Cumartesi', '').str.replace(' Pazar', '').str.replace('rtesi','')

case_report['VAKAYA CIKIS TARIH SAAT']= case_report['Vakaya Çıkış Tarihi'] +' '+ case_report['Vakaya Çıkış Saati']

case_report['Ambulans Plaka']

move_report['Plaka']= move_report['Plaka'].str.upper().str.replace(' ', '')

move_report[['Plaka', 'Başlangıç Tarihi']]

move_report['Başlangıç Tarihi'].dropna(how='any', inplace=True)

move_report.rename(columns={'Plaka':'Ambulans Plaka'},inplace= True)

move_report['Başlangıç Tarihi']= move_report['Başlangıç Tarihi'].fillna(0)

move_report= move_report[move_report['Başlangıç Tarihi'] != 0]





case_report['VAKAYA CIKIS TARIH SAAT']

move_report['Başlangıç Tarihi']= pd.to_datetime(move_report['Başlangıç Tarihi'],format='%d-%m-%Y %H:%M:%S')

case_report['VAKAYA CIKIS TARIH SAAT']= pd.to_datetime(case_report['VAKAYA CIKIS TARIH SAAT'],format='%d-%m-%Y %H:%M:%S' )
#The format code for year is %Y not %YYYY

case_report['Ambulans Plaka']

move_report= move_report[['Ambulans Plaka', 'Başlangıç Tarihi']]

move_report

move_report[move_report['Ambulans Plaka'] == '34HUL734']

for i in range(len(case_report)):
  temp_df= move_report[move_report['Ambulans Plaka']== case_report.iloc[i]['Ambulans Plaka']]
  temp_df= temp_df[temp_df['Başlangıç Tarihi'] > case_report.iloc[i]['VAKAYA CIKIS TARIH SAAT']]
  if len(temp_df) > 0:
    case_report.loc[i, 'GPS Bazlı Çıkış Tarihi']= temp_df['Başlangıç Tarihi'].min()

case_report[['Ekip No','Ambulans Plaka', 'VAKAYA CIKIS TARIH SAAT', 'GPS Bazlı Çıkış Tarihi']]

