# -*- coding: utf-8 -*-
"""team_sign_times.ipynb

Automatically generated by Colab.

"""

import pandas as pd
import numpy as np

excel_file= pd.ExcelFile('/staff_sign_report.xlsx')

dataframes= {sheet_name:excel_file.parse(sheet_name) for sheet_name in excel_file.sheet_names}

dataframes.keys()

signs_df= dataframes['Sheet1'].copy()

[i for i in signs_df.columns]

signs_df.drop(columns=['Giriş T..1','Giriş T..2' ], inplace=True)
signs_df.drop(columns= ['Unnamed: 14','Unnamed: 15','Unnamed: 16'], inplace=True)

signs_df['Giriş T.'] = pd.to_datetime(signs_df['Giriş T.'])

signs_df['Giriş Saati']= signs_df['Giriş T.'].dt.strftime('%H:%M:%S')

signs_df['Başlama T.']= pd.to_datetime(signs_df['Başlama T.'])
signs_df['Başlama Saati']= signs_df['Başlama T.'].dt.strftime('%H:%M:%S')
signs_df['Bitiş T.']= pd.to_datetime(signs_df['Bitiş T.'])
signs_df['Bitiş Saati']= signs_df['Bitiş T.'].dt.strftime('%H:%M:%S')

signs_df['Başlama Saati'].unique()

#signs_df.drop(columns= "GiriŞ Başlama Farkı", inplace=True)

signs_df['Giriş Başlama Farkı']= signs_df['Giriş T.'] - signs_df['Başlama T.']
signs_df['Giriş Başlama Farkı'] = signs_df['Giriş Başlama Farkı'].dt.total_seconds() / 60
signs_df['Giriş Başlama Farkı'] = signs_df['Giriş Başlama Farkı'].round(2)

long_difference= signs_df[signs_df['Giriş Başlama Farkı']>180]
other_teams= signs_df[~(signs_df['Ekip Kodu'].str.len()<5)]
signs_df= signs_df[signs_df['Giriş Başlama Farkı']<180]
signs_df= signs_df[signs_df['Ekip Kodu'].str.len()<5]



signs_df= pd.concat([other_teams[other_teams['Ekip Kodu'].str.contains('KÇK|ESY|BAG|FTH|STG|BHC')], signs_df], ignore_index=True)
other_teams= other_teams[~(other_teams['Ekip Kodu'].str.contains('KÇK|ESY|BAG|FTH|STG|BHC'))]


signs_df.sort_values(by='Giriş Başlama Farkı', ascending=False, inplace=True)

signs_df['Value']= 1

#round signs_df['Giriş Saati'] to the smaller 10min

signs_df['Giriş Saat Aralığı'] = pd.to_datetime(signs_df['Giriş Saati']).dt.floor('10min').dt.strftime('%H:%M:%S')



sekiz_baslama= signs_df[signs_df['Başlama Saati']=='08:00:00']
yirmi_baslama= signs_df[signs_df['Başlama Saati']=='20:00:00']
diger_baslama= signs_df[~signs_df['Başlama Saati'].isin(['08:00:00','20:00:00'])]



sekiz_pivot= sekiz_baslama.pivot_table(index='Başlama T.', columns= 'Giriş Saat Aralığı', values='Value', aggfunc='sum').fillna(0)
yirmi_pivot= yirmi_baslama.pivot_table(index='Başlama T.', columns= 'Giriş Saat Aralığı', values='Value', aggfunc='sum').fillna(0)
diger_pivot= diger_baslama.pivot_table(index='Başlama T.', columns= 'Giriş Saat Aralığı', values='Value', aggfunc='sum').fillna(0)

#diger_baslama.groupby(pd.Grouper(key='Giriş Saati', freq='10Min')).agg({'Value':'sum', 'Giriş Başlama Farkı':'mean'})

sekiz_pivot['Toplam']= sekiz_pivot.sum(axis=1)
yirmi_pivot['Toplam']= yirmi_pivot.sum(axis=1)
diger_pivot['Toplam']= diger_pivot.sum(axis=1)



sekiz_pivot.to_excel('sekiz_pivot.xlsx')
yirmi_pivot.to_excel('yirmi_pivot.xlsx')
diger_pivot.to_excel('diger_pivot.xlsx')

long_difference.to_excel('uzun_farklar.xlsx')
other_teams.to_excel('diger_takimlar.xlsx')

