def find_district():
  
  """
  Based on the addresses have been taken, this function creates two columns to write the districts and neighbourhoods
  
  """

  import pandas as pd
  import numpy as np
  import warnings
  warnings.filterwarnings('ignore')

  import os

  # import Excel File and select the dataframe
  file_path= str(input('Please add the file path here: '))
  excel_file= pd.ExcelFile(file_path)

  dataframes= {sheet_name: excel_file.parse(sheet_name) for sheet_name in excel_file.sheet_names}
  print(list(dataframes.keys()))
  sheet_path = str(input(f'Please add the sheet path here: '))
  df= dataframes[sheet_path]

  # Created a temporary file to not harm the original dataframe
  df_temp= df.copy()


  # Make columns uppercase and remove the blanks
  df_temp.columns = [col.strip().upper() for col in df_temp.columns]

  # Select the address column
  column_path= str(input('Please add the address column name here: '))
  column_path= column_path.replace('-','').replace('Ç', 'C').replace('Ğ', 'G').replace('İ', 'I').replace('Ö', 'O').replace('Ş', 'S').replace('Ü', 'U').strip().upper()
  
  # New columns without any unnecessarities
  columns_list= []
  for i in df_temp.columns:
    i= i.replace('-','').replace('Ç', 'C').replace('Ğ', 'G').replace('İ', 'I').replace('Ö', 'O').replace('Ş', 'S').replace('Ü', 'U').strip()
    columns_list.append(i)

  df_temp.columns= columns_list #####################################

  df_temp[column_path].fillna('UNKNOWN', inplace= True)

  # Because of column_path written by user, an extra work has been done on it
  df_temp[column_path]= df_temp[column_path].str.upper().str.replace('-', ' ').str.replace('Ç', 'C').str.replace('Ğ', 'G').str.replace('İ', 'I').str.replace('Ö', 'O').str.replace('Ş', 'S').str.replace('Ü', 'U').str.strip()

  df_temp[column_path]= df_temp[column_path].str.strip().str.upper()

  # Dictionary keys of districts and neighbours for each side of Istanbul
  europe_neighbourhoods= {'ARNAVUTKOY': {'DELIKLIKAYA', 'CILINGIR', 'TAYAKADIN', 'HADIMKOY', 'HICRET', 'OMERLI', 'TERKOS', 'KARABURUN', 'YENIKOY', 'BAKLALI', 'YESILBAYIR', 'DURUSU', 'BALABAN', 'BOYALIK', 'MARESAL FEVZI CAKMAK', 'HASTANE', 'ANADOLU', 'IMRAHOR', 'YAVUZ SELIM', 'KARLIBAYIR', 'HARACCI', 'FATIH', 'ARNAVUTKOY MERKEZ', 'YUNUS EMRE', 'BOLLUCA', 'MAVIGOL', 'BOGAZKOY ISTIKLAL', 'HACIMASLI', 'MEHMET AKIF ERSOY', 'MUSTAFA KEMAL PASA', 'ATATURK', 'YASSIOREN', 'TASOLUK', 'DURSUNKOY', 'ISLAMBEY', 'ADNAN MENDERES', 'SAZLIBOSNA', 'NENEHATUN'}, 'AVCILAR': {'UNIVERSITE', 'CIHANGIR', 'MERKEZ', 'DENIZKOSKLER', 'AMBARLI', 'FIRUZKOY', 'TAHTAKALE', 'YESILKENT', 'MUSTAFA KEMAL PASA', 'GUMUSPALA'}, 'BAGCILAR': {'GUNESLI', 'DEMIRKAPI', 'YENIMAHALLE', 'YENIGUN', 'BAGLAR', 'KIRAZLI', '15 TEMMUZ', 'HURRIYET', 'YILDIZTEPE', 'FATIH', 'CINAR', '100. YIL', 'SANCAKTEPE', 'INONU', 'GOZTEPE', 'KEMALPASA', 'MERKEZ', 'FEVZI CAKMAK', 'KAZIM KARABEKIR', 'MAHMUTBEY', 'BARBAROS', 'YAVUZ SELIM'}, 'BAHCELIEVLER': {'SIRINEVLER', 'FEVZI CAKMAK', 'CUMHURIYET', 'HURRIYET', 'SOGANLI', 'BAHCELIEVLER', 'SIYAVUSPASA', 'KOCASINAN', 'COBANCESME', 'YENIBOSNA', 'ZAFER'}, 'BAKIRKOY': {'SAKIZAGACI', 'ATAKOY 1. KISIM', 'ZEYTINLIK', 'SENLIKKOY', 'KARTALTEPE', 'YENIMAHALLE', 'ATAKOY 7 8 9 10. KISIM', 'ATAKOY 3 4 11. KISIM', 'YESILYURT', 'ATAKOY 2 5 6. KISIM', 'CEVIZLIK', 'ZUHURATBABA', 'YESILKOY', 'OSMANIYE', 'BASINKOY'}, 'ZEYTINBURNU': {'YESILTEPE', 'MALTEPE', 'TELSIZ', 'GOKALP', 'BESTELSIZ', 'CIRPICI', 'SEYITNIZAM', 'MERKEZEFENDI', 'VELIEFENDI', 'SUMER', 'YENIDOGAN', 'NURIPASA', 'KAZLICESME'}, 'BASAKSEHIR': {'ZIYA GOKALP', 'BASAK', 'KAYABASI', 'ALTINSEHIR', 'SAMLAR', 'GUVERCINTEPE', 'BAHCESEHIR 1. KISIM', 'BAHCESEHIR 2. KISIM', 'SAHINTEPE', 'BASAKSEHIR'}, 'BAYRAMPASA': {'ISMET PASA', 'KARTALTEPE', 'CEVATPASA', 'YILDIRIM', 'MURATPASA', 'KOCATEPE', 'TERAZIDERE', 'ALTINTEPSI', 'YENIDOGAN', 'ORTA', 'VATAN'}, 'BESIKTAS': {'LEVAZIM', 'ULUS', 'VISNEZADE', 'NISBETIYE', 'BALMUMCU', 'YILDIZ', 'KONAKLAR', 'AKAT', 'MECIDIYE', 'ARNAVUTKOY', 'ABBASAGA', 'SINANPASA', 'GAYRETTEPE', 'CIHANNUMA', 'ETILER', 'BEBEK', 'LEVENT', 'KULTUR', 'DIKILITAS', 'KURUCESME', 'TURKALI', 'MURADIYE', 'ORTAKOY'}, 'BEYLIKDUZU': {'GURPINAR', 'KAVAKLI', 'CUMHURIYET', 'YAKUPLU', 'SAHIL', 'MARMARA', 'ADNAN KAHVECI', 'BUYUKSEHIR', 'DEREAGZI', 'BARIS'}, 'BEYOGLU': {'CATMA MESCIT', 'GUMUSSUYU', 'OMER AVNI', 'KALYONCU KULLUGU', 'KUCUK PIYALE', 'HACIMIMI', 'ISTIKLAL', 'PIYALEPASA', 'EMEKYEMEZ', 'KATIP MUSTAFA CELEBI', 'FETIHTEPE', 'EVLIYA CELEBI', 'CAMIIKEBIR', 'SUTLUCE', 'BOSTAN', 'YENISEHIR', 'PIRI PASA', 'HUSEYINAGA', 'ARAP CAMI', 'KECECI PIRI', 'HALICIOGLU', 'SEHIT MUHTAR', 'KAMER HATUN', 'PURTELAS', 'ORNEKTEPE', 'KAPTANPASA', 'KULOGLU', 'CIHANGIR', 'ASMALI MESCIT', 'YAHYA KAHYA', 'BEREKETZADE', 'CUKUR', 'KILICALI PASA', 'TOMTOM', 'BULBUL', 'SURURI', 'FIRUZAGA', 'KADIMEHMET EFENDI', 'BEDRETTIN', 'KULAKSIZ', 'HACIAHMET', 'KEMANKES KARAMUSTAFA PASA', 'MUEYYETZADE', 'KOCATEPE', 'SAHKULU'}, 'BUYUKCEKMECE': {'ULUS', 'MIMAR SINAN MERKEZ', 'EKINOBA', '19 MAYIS', 'KARAAGAC', 'PINARTEPE', 'MURAT CESME', 'MIMAROBA', 'KAMILOBA', 'CAKMAKLI', 'ALKENT', 'YENIMAHALLE', 'TURKOBA', 'AHMEDIYE', 'GUZELCE', 'HURRIYET', 'DIZDARIYE', 'CELALIYE', 'FATIH', 'ATATURK', 'SINANOBA', 'CUMHURIYET', 'BAHCELIEVLER', 'KUMBURGAZ'}, 'CATALCA': {'IZZETTIN', 'BASAK', 'ORENCIK', 'OKLALI', 'SUBASI', 'FERHATPASA', 'KARAMANDERE', 'YAYLACIK', 'CAKIL', 'INCEGIZ', 'ELBASAN', 'CIFTLIKKOY', 'GUMUSPINAR', 'NAKKAS', 'CELEPKOY', 'KARACAKOY', 'KALEICI', 'AYDINLAR', 'KALFA', 'IHSANIYE', 'ORCUNLU', 'OVAYENICE', 'FATIH', 'CANAKCA', 'KABAKCA', 'AKALAN', 'ATATURK', 'HISARBEYLI', 'HALLACLI', 'ORMANLI', 'KESTANELIK', 'YALIKOY', 'MURATBEY MERKEZ', 'DAGYENICE', 'GOKCEALI', 'BAHSAYIS'}, 'ESENLER': {'KEMER', 'NINE HATUN', 'DAVUTPASA', 'CIFTE HAVUZLAR', 'FEVZI CAKMAK', 'MENDERES', '15 TEMMUZ', 'ORUCREIS', 'KAZIM KARABEKIR', 'FATIH', 'TURGUT REIS', 'BIRLIK', 'HAVAALANI', 'MIMAR SINAN', 'NAMIK KEMAL', 'YAVUZ SELIM', 'TUNA'}, 'ESENYURT': {'ASIK VEYSEL', 'AKSEMSEDDIN', 'SULEYMANIYE', 'ESENKENT', 'YENIKENT', 'SULTANIYE', 'INCIRTEPE', 'ISTIKLAL', 'YESILKENT', 'ZAFER', 'GUZELYURT', 'KOZA', 'MEVLANA', 'SAADETDERE', 'OSMANGAZI', 'SELAHADDIN EYYUBI', 'GOKEVLER', 'SEHITLER', 'PINAR', 'NECIP FAZIL KISAKUREK', 'ORNEK', 'ARDICLI', 'BALIKYOLU', 'TURGUT OZAL', 'HURRIYET', 'AKEVLER', 'FATIH', 'CINAR', 'YUNUS EMRE', 'PIRI REIS', 'MEHTERCESME', 'INONU', 'BARBAROS HAYRETTIN PASA', 'BATTALGAZI', 'MEHMET AKIF ERSOY', 'NAMIK KEMAL', 'ATATURK', 'TALATPASA', 'UCEVLER', 'CUMHURIYET', 'BAGLARCESME', 'ORHAN GAZI', 'AKCABURGAZ'}, 'EYUPSULTAN': {'CIFTALAN', 'NISANCI', 'MITHATPASA', 'AGACLI', 'DUGMECILER', 'RAMI YENI', 'ESENTEPE', 'CIRCIR', 'PIRINCCI', 'IHSANIYE', 'ODAYERI', 'ALIBEYKOY', 'TOPCULAR', 'YESILPINAR', 'EMNIYETTEPE', 'GUZELTEPE', 'AKPINAR', 'SILAHTARAGA', 'DEFTERDAR', 'MERKEZ', 'AKSEMSETTIN', 'ISLAMBEY', 'GOKTURK MERKEZ', 'RAMI CUMA', 'ISIKLAR', 'MIMAR SINAN', 'SAKARYA', '5. LEVENT', 'KARADOLAP'}, 'FATIH': {'KATIP KASIM', 'ATIKALI', 'SEYYID OMER', 'SEHREMINI', 'SULEYMANIYE', 'KUCUK AYASOFYA', 'ZEYREK', 'AYVANSARAY', 'MIMAR KEMALETTIN', 'HASEKI SULTAN', 'MOLLA FENARI', 'CIBALI', 'HIRKA I SERIF', 'KARAGUMRUK', 'TOPKAPI', 'TAHTAKALE', 'ALEMDAR', 'BALABANAGA', 'BEYAZIT', 'MOLLA HUSREV', 'RUSTEM PASA', 'MESIHPASA', 'MUHSINE HATUN', 'KALENDERHANE', 'MIMAR HAYRETTIN', 'CERRAHPASA', 'CANKURTARAN', 'HOBYAR', 'DEMIRTAS', 'HOCA GIYASETTIN', 'YAVUZ SULTAN SELIM', 'NISANCA', 'SILIVRIKAPI', 'BINBIRDIREK', 'ISKENDERPASA', 'MEVLANAKAPI', 'HOCA PASA', 'SARIDEMIR', 'YEDIKULE', 'SURURI', 'KOCA MUSTAFAPASA', 'MOLLA GURANI', 'AKSEMSETTIN', 'BALAT', 'KEMAL PASA', 'MERCAN', 'AKSARAY', 'ALI KUSCU', 'DERVIS ALI', 'SULTAN AHMET', 'SUMBUL EFENDI'}, 'GAZIOSMANPASA': {'KARLITEPE', 'MEVLANA', 'FEVZI CAKMAK', 'MERKEZ', 'YENI MAHALLE', 'HURRIYET', 'SARIGOL', 'YENIDOGAN', 'YILDIZTABYA', 'BARBAROS HAYRETTINPASA', 'KAZIM KARABEKIR', 'KARADENIZ', 'BAGLARBASI', 'SEMSIPASA', 'KARAYOLLARI', 'PAZARICI'}, 'GUNGOREN': {'AKINCILAR', 'MARESAL CAKMAK', 'MERKEZ', 'SANAYI', 'TOZKOPARAN', 'MEHMET NESIH OZMEN', 'HAZNEDAR', 'GUVEN', 'GUNESTEPE', 'ABDURRAHMAN NAFIZ GURMAN', 'GENCOSMAN'}, 'KAGITHANE': {'SULTAN SELIM', 'TELSIZLER', 'GURSEL', 'SEYRANTEPE', 'EMNIYET', 'GULTEPE', 'ORTABAYIR', 'SIRINTEPE', 'HURRIYET', 'CAGLAYAN', 'MEHMET AKIF ERSOY', 'TALATPASA', 'YESILCE', 'MERKEZ', 'HAMIDIYE', 'CELIKTEPE', 'YAHYA KEMAL', 'HARMANTEPE', 'NURTEPE'}, 'KUCUKCEKMECE': {'ATAKENT', 'TEVFIK BEY', 'KARTALTEPE', 'HALKALI', 'BESYOL', 'YARIMBURGAZ', 'MEHMET AKIF', 'ISTASYON', 'SOGUTLU CESME', 'GULTEPE', 'KANARYA', 'YENI MAHALLE', 'FATIH', 'SULTAN MURAT', 'YESILOVA', 'INONU', 'ATATURK', 'KEMALPASA', 'FEVZI CAKMAK', 'CUMHURIYET', 'CENNET'}, 'SARIYER': {'SARIYER MERKEZ', 'GUMUSDERE', 'POLIGON', 'FATIH SULTAN MEHMET', 'KIRECBURNU', 'AYAZAGA', 'TARABYA', 'RESITPASA', 'BAHCEKOY YENI', 'MADEN', 'YENI', 'YENIKOY', 'FERAHEVLER', 'KUMKOY', 'CAMLITEPE', 'USKUMRUKOY', 'MASLAK', 'PINAR', 'DEMIRCI', 'RUMELIFENERI', 'ZEKERIYAKOY', 'BAHCEKOY KEMER', 'BUYUKDERE', 'ISTINYE', 'KISIRKAYA', 'KOCATAS', 'EMIRGAN', 'CAYIRBASI', 'GARIPCE', 'BAHCEKOY MERKEZ', 'DARUSSAFAKA', 'CUMHURIYET', 'BALTALIMANI', 'RUMELI KAVAGI', 'KAZIM KARABEKIR', 'HUZUR', 'RUMELI HISARI', 'PTT EVLERI'}, 'SILIVRI': {'GAZITEPE', 'GUMUSYAKA', 'BUYUK KILICLI', 'FENER', 'KURFALLI', 'AKOREN', 'YENI', 'KAVAKLI ISTIKLAL', 'SELIMPASA', 'ALIBEY', 'PIRI MEHMET PASA', 'CELTIK', 'BALABAN', 'KUCUK SINEKLI', 'SEYMEN', 'CAYIRDERE', 'KAVAKLI HURRIYET', 'SAYALAR', 'FATIH', 'DEGIRMENKOY ISMETPASA', 'DANAMANDIRA', 'KADIKOY', 'YOLCATI', 'CUMHURIYET', 'SEMIZKUMLAR', 'ALIPASA', 'CANTA SANCAKTEPE', 'ORTAKOY', 'BUYUK CAVUSLU', 'MIMAR SINAN', 'BUYUK SINEKLI', 'DEGIRMENKOY FEVZIPASA', 'BEYCILER'}, 'SULTANGAZI': {'HABIBLER', 'UGUR MUMCU', 'CUMHURIYET', '50. YIL', 'YAYLA', 'ISMETPASA', 'CEBECI', 'GAZI', 'SULTANCIFTLIGI', 'MALKOCOGLU', 'ESENTEPE', '75. YIL'}, 'SISLI': {'TESVIKIYE', '19 MAYIS', 'HALIL RIFAT PASA', 'ESKISEHIR', 'PASA', 'MECIDIYEKOY', 'GULBAHAR', 'KUSTEPE', 'FULYA', 'MAHMUT SEVKET PASA', 'ESENTEPE', 'ERGENEKON', 'HARBIYE', 'HALIDE EDIP ADIVAR', 'INONU', 'HALASKARGAZI', 'DUATEPE', 'FERIKOY', 'MERKEZ', 'CUMHURIYET', 'MESRUTIYET', 'YAYLA', 'BOZKURT'}, 'UNKNOWN':{'UNKNOWN'}}
  anatolia_neighbourhoods= {'UMRANIYE': {'ATAKENT', 'ASAGI DUDULLU', 'TATLISU', 'ESENKENT', 'ESENSEHIR', 'FATIH SULTAN MEHMET', 'CAKMAK', 'ISTIKLAL', 'INKILAP', 'DUDULLU', 'MEHMET AKIF', 'HEKIMBASI', 'YUKARI DUDULLU', 'TOPAGACI', 'ESENEVLER', 'FINANSKENT', 'SITE', 'SERIFALI', 'DUMLUPINAR', 'CEMIL MERIC', 'TEPEUSTU', 'YAMANEVLER', 'MADENLER', 'DUDULLU OSB', 'ALTINSEHIR', 'SARAY', 'NECIP FAZIL', 'NAMIK KEMAL', 'ASAGIDUDULLU', 'ATATURK', 'PARSELLER', 'CIFT MAHALLE BILGISI', 'TANTAVI', 'IHLAMURKUYU', 'ADEM YAVUZ', 'KAZIM KARABEKIR', 'CAMLIK', 'ARMAGANEVLER', 'ELMALIKENT', 'YUKARIDUDULLU', 'HUZUR'}, 'KARTAL': {'KORDONBOYU', 'ORHANTEPE', 'SOGANLIK YENI', 'ORTA', 'ATALAR', 'YUKARI', 'GUMUSPINAR', 'ESENTEPE', 'PETROL IS', 'HURRIYET', 'YALI', 'CEVIZLI', 'CAVUSOGLU', 'UGUR MUMCU', 'YAKACIK YENI', 'YAKACIK CARSI', 'CUMHURIYET', 'KARLIKTEPE', 'TOPSELVI', 'SOGANLIK', 'YUNUS'}, 'CEKMEKOY': {'ALEMDAG', 'SULTANCIFTLIGI', 'SOGUKPINAR', 'MEHMET AKIF', 'BELIRTILMEMIS', 'OMERLI', 'NISANTEPE', 'TASDELEN', 'RESADIYE', 'AYDINLAR', 'HUSEYINLI', 'GUNGOREN', 'KIRAZLIDERE', 'SIRAPINAR', 'CATALMESE', 'MERKEZ', 'HAMIDIYE', 'CUMHURIYET', 'CAMLIK', 'MIMAR SINAN', 'EKSIOGLU', 'KOCULLU'}, 'SANCAKTEPE': {'VEYSEL KARANI', 'SAFA', 'SARIGAZI', 'PASAKOY', 'BELIRTILMEMIS', 'MEVLANA', 'OSMANGAZI', 'MERVE', 'KEMAL TURKLER', 'EYUP SULTAN', 'MECLIS', 'FATIH', 'YUNUS EMRE', 'INONU', 'ATATURK', 'EMEK', 'AKPINAR', 'ABDURRAHMANGAZI', 'HILAL', 'YENIDOGAN'}, 'KADIKOY': {'KOZYATAGI', '19 MAYIS', 'RASIMPASA', 'FENERYOLU', 'MERDIVENKOY', 'CADDEBOSTAN', 'CAFERAGA', 'BELIRTILMEMIS', 'BOSTANCI', 'ZUHTUPASA', 'DUMLUPINAR', 'KOSUYOLU', 'ERENKOY', 'FIKIRTEPE', 'SUADIYE', 'GOZTEPE', 'FENERBAHCE', 'SAHRAYI CEDIT', 'OSMANAGA', 'ACIBADEM', 'EGITIM', 'HASANPASA'}, 'PENDIK': {'YAYALAR', 'ESENYALI', 'ORTA', 'SEYHLI', 'BELIRTILMEMIS', 'BATI', 'AHMET YESEVI', 'YENI', 'VELIBABA', 'YENISEHIR', 'KURNA', 'EMIRLI', 'KURTDOGMUS', 'SULUNTEPE', 'KAYNARCA', 'GOCBEYLI', 'DUMLUPINAR', 'KURTKOY', 'ESENLER', 'DOGU', 'SAPAN BAGLARI', 'GUZELYALI', 'FATIH', 'RAMAZANOGLU', 'CAMCESME', 'KAVAKPINAR', 'FEVZI CAKMAK', 'ORHANGAZI', 'SANAYI', 'BAHCELIEVLER', 'HARMANDERE', 'CAMLIK', 'GULLU BAGLAR', 'YESILBAGLAR', 'ERTUGRUL GAZI', 'BALLICA', 'CINARDERE'}, 'ATASEHIR': {'ASIK VEYSEL', 'FERHATPASA', 'BELIRTILMEMIS', 'FETIH', 'YENISEHIR', 'MEVLANA', 'KUCUKBAKKALKOY', 'YENI SAHRA', 'YENICAMLICA', 'YENI CAMLICA', 'MUSTAFA KEMAL', 'ORNEK', 'ICERENKOY', 'ASIKVEYSEL', 'INONU', 'ATATURK', 'ESATPASA', 'BARBAROS', 'MIMAR SINAN', 'KAYISDAGI'}, 'USKUDAR': {'SELAMI ALI', 'SULTANTEPE', 'KUPLUCE', 'KANDILLI', 'KUCUKSU', 'KUCUK CAMLICA', 'SELIMIYE', 'ICADIYE', 'YAVUZTURK', 'MURAT REIS', 'KISIKLI', 'FERAH', 'AHMEDIYE', 'UNALAN', 'KULELI', 'BURHANIYE', 'VALIDE I ATIK', 'ALTUNIZADE', 'MEHMET AKIF ERSOY', 'BEYLERBEYI', 'GUZELTEPE', 'BULGURLU', 'KIRAZLITEPE', 'CUMHURIYET', 'SALACAK', 'ZEYNEP KAMIL', 'BAHCELIEVLER', 'CENGELKOY', 'AZIZ MAHMUT HUDAYI', 'BARBAROS', 'ACIBADEM', 'MIMAR SINAN', 'KUZGUNCUK'}, 'SULTANBEYLI': {'MEHMET AKIF', 'AHMET YESEVI', 'ABDURRAHMANGAZI', 'ORHANGAZI', 'MECIDIYE', 'HAMIDIYE', 'AKSEMSETTIN', 'TURGUT REIS', 'FATIH', 'TURGUTREIS', 'NECIP FAZIL', 'MIMAR SINAN', 'YAVUZ SELIM', 'BATTALGAZI', 'ADIL', 'BELIRTILMEMIS', 'HASANPASA'}, 'MALTEPE': {'ZUMRUTEVLER', 'ALTAYCESME', 'ESENKENT', 'ALTINTEPE', 'IDEALTEPE', 'BELIRTILMEMIS', 'BASIBUYUK', 'GULENSU', 'AYDINEVLER', 'KUCUKYALI', 'YALI', 'CINAR', 'CEVIZLI', 'FEYZULLAH', 'BUYUKBAKKALKOY', 'BAGLARBASI', 'FINDIKLI', 'GULSUYU', 'GIRNE'}, 'BEYKOZ': {'GUMUSSUYU', 'ISHAKLI', 'GOKSU', 'GOLLU', 'ALIBAHADIR', 'ANADOLUHISARI', 'BOZHANE', 'DERESEKI', 'BELIRTILMEMIS', 'ANADOLUKAVAGI', 'ANADOLU KAVAGI', 'ANADOLU FENERI', 'AKBABA', 'PASABAHCE', 'ACARLAR', 'YENIMAHALLE', 'MAHMUT SEVKET PASA', 'KAYNARCA', 'ANADOLU HISARI', 'POLONEZKOY', 'CAMLIBAHCE', 'CIFTLIK', 'GORELE', 'POYRAZKOY', 'OGUMCE', 'CIGDEM', 'YENI MAHALLE', 'INCIRKOY', 'KILICLI', 'SOGUKSU', 'TOKATKOY', 'FATIH', 'CUBUKLU', 'ZERZAVATCI', 'GOZTEPE', 'PASAMANDIRA', 'KAVACIK', 'YALIKOY', 'MERKEZ', 'BAKLACI', 'CUMHURIYET', 'MAHMUTSEVKETPASA', 'RUZGARLIBAHCE', 'KANLICA', 'ORNEKKOY', 'CENGELDERE', 'ORTACESME', 'YAVUZ SELIM', 'RIVA', 'ELMALI'}, 'SILE': {'KUMBABA', 'ERENLER', 'UVEZLI', 'SORTULLU', 'GOKSU', 'KARAMANDERE', 'KURFALLI', 'GOCE', 'AVCIKORU', 'HACI KASIM', 'CELEBI', 'AHMETLI', 'BELIRTILMEMIS', 'KORUCU', 'SUAYIPLI', 'KOMURLUK', 'HACILLI', 'YENIKOY', 'KURNA', 'DOGANCILI', 'KARAKIRAZ', 'TEKE', 'AKCAKESE', 'SAHILKOY', 'KIZILCA', 'KERVANSARAY', 'KARACAKOY', 'BICKIDERE', 'CAVUS', 'KALEM', 'ISAKOY', 'ALACALI', 'IMRENLI', 'YAKA', 'ESENCELI', 'ORUCOGLU', 'ULUPELIT', 'CAYIRBASI', 'SOFULAR', 'AGACDERE', 'AGVA', 'BOZGOCA', 'CENGILLI', 'CATAKLI', 'DARLIK', 'YAZIMANAYIR', 'IMRENDERE', 'OVACIK', 'BALIBEY', 'MESRUTIYET', 'DEGIRMENCAYIRI', 'CIFT MAHALLE BILGISI', 'KADIKOY', 'GOKMASLI', 'HASANLI', 'YESILVADI', 'GEREDELI', 'KABAKOZ', 'OSMANKOY', 'BUCAKLI', 'KARABEYLI', 'SATMAZLI', 'SOGULLU', 'HACIKASIM'}, 'TUZLA': {'CAMI', 'ICMELER', 'DERI OSB', 'ORTA', 'BELIRTILMEMIS', 'EVLIYA CELEBI', 'SIFA', 'ISTASYON', 'POSTANE', 'ANADOLU', 'ORHANLI', 'AYDINLI', 'FATIH', 'AKFIRAT', 'TEPEOREN', 'AYDINTEPE', 'MESCIT', 'YAYLA', 'MIMAR SINAN'}, 'ADALAR': {'MADEN', 'KINALIADA', 'BURGAZADA', 'HEYBELIADA', 'NIZAM', 'BELIRTILMEMIS'}, 'SISLI': {'GULBAHAR', 'ESENTEPE', 'MERKEZ'}, 'SARIYER': {'MASLAK', 'BALTALIMANI', 'GARIPCE'}, 'UNKNOWN':{'UNKNOWN'}}


  # This function mainly compares the Address area with the dictionary keys, and finds areas we want
  def find_district(address, district_list):
    for district in district_list:
        if district in address:
            return district
    return np.nan
  
  # Asks user about which side of Istanbul wanted to be searched, that question reduces the working time for the code
  region= str(input('Lütfen temizlemek istediğiniz bölge adını yazınız(ANADOLU - AVRUPA): '))

  if region.upper()== 'ANADOLU':

    # To find the district names in the address field
    district_list= list(anatolia_neighbourhoods.keys())

    # First we find districts, so that will help us to use them as keys to find neighbourhoods,
    # Otherwise there are a hundreds of similar named neighbourhoods in other districts, we have to avoid this mess
    df_temp['District']= df_temp[column_path].apply(find_district, district_list=district_list)
    df_temp['District'].fillna('UNKNOWN', inplace= True)

    # Neighbourhoods
    df_temp['Neighbourhood'] = df_temp.apply(lambda row: find_district(row[column_path], district_list=anatolia_neighbourhoods[row['District']]), axis=1)


  if region.upper() == 'AVRUPA':

    district_list= list(europe_neighbourhoods.keys())

    df_temp['District']= df_temp[column_path].apply(find_district, district_list=district_list)
    df_temp['District'].fillna('UNKNOWN', inplace= True)

    # Neighbourhoods

    df_temp['Neighbourhood'] = df_temp.apply(lambda row: find_district(row[column_path], district_list=europe_neighbourhoods[row['District']]), axis=1)


  file_name= str(input('Please Select a File Name: '))
  df_temp.to_excel(f'{file_name}.xlsx')

  return "Many loves from Muhammed KAYA!"