# -*- coding: utf-8 -*-
"""denetim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jOtYI0b_1Z1pJzYySfxVcReoB0kLyAzC
"""

import pandas as pd
import numpy as np

from IPython.display import display

path= 'data/case_reports/europe/2024/monthly/'

df_may = pd.ExcelFile(path+'5-MAYIS 2024 AVR ASOS TANIDÖNÜŞTÜRÜLMÜŞ DEFTER.xlsx')
df_june = pd.ExcelFile(path+'6-HAZİRAN 2024 AVR ASOS TANIDÖNÜŞTÜRÜLMÜŞ DEFTER.xlsx')

dataframe_may= df_may.parse(df_may.sheet_names[1])
dataframe_june= df_june.parse(df_june.sheet_names[1])

df= pd.concat([dataframe_may,dataframe_june])

df.head(20)

df['Sonuç'].unique()

df['Ekipteki Kişiler']

df= df[(df['Sonuç'] == 'Başka Araçla Nakil') | (df['Sonuç'] == 'Yaralı Yok') | (df['Sonuç'] == 'Asılsız İhbar')]



df_baska = df[(df['Sonuç'] == 'Başka Araçla Nakil')]
df_yarali = df[(df['Sonuç'] == 'Yaralı Yok')]
df_asilsız = df[(df['Sonuç'] == 'Asılsız İhbar')]
df_baska['TEAM']= df_baska['Ekipteki Kişiler'].str.split(',')
df_yarali['TEAM']= df_yarali['Ekipteki Kişiler'].str.split(',')
df_asilsız['TEAM']= df_asilsız['Ekipteki Kişiler'].str.split(',')

df_baska = df_baska.explode('TEAM')
df_yarali = df_yarali.explode('TEAM')
df_asilsız = df_asilsız.explode('TEAM')
df_baska['TEAM'] = df_baska['TEAM'].str.strip()
df_yarali['TEAM'] = df_yarali['TEAM'].str.strip()
df_asilsız['TEAM'] = df_asilsız['TEAM'].str.strip()

df_baska['TEAM']= df_baska['TEAM'].apply(lambda x: x.split(' - ')[0])
df_yarali['TEAM']= df_yarali['TEAM'].apply(lambda x: x.split(' - ')[0])
df_asilsız['TEAM']= df_asilsız['TEAM'].apply(lambda x: x.split(' - ')[0])

df_baska= df_baska[~(df_baska['TEAM'].str.contains('Sürücü'))]
df_yarali= df_yarali[~(df_yarali['TEAM'].str.contains('Sürücü'))]
df_asilsız= df_asilsız[~(df_asilsız['TEAM'].str.contains('Sürücü'))]

df_baska['VALUE']= 1
df_yarali['VALUE']= 1
df_asilsız['VALUE']= 1

"""df_baska.groupby('TEAM').agg({'VALUE':'sum'}).sort_values('VALUE',ascending=False).reset_index().to_excel('C:/Users/mkaya/OneDrive/Masaüstü/BASKA.xlsx')
df_yarali.groupby('TEAM').agg({'VALUE':'sum'}).sort_values('VALUE',ascending=False).reset_index().to_excel('C:/Users/mkaya/OneDrive/Masaüstü/YARALI.xlsx')
df_asilsız.groupby('TEAM').agg({'VALUE':'sum'}).sort_values('VALUE',ascending=False).reset_index().to_excel('C:/Users/mkaya/OneDrive/Masaüstü/ASILSIZ.xlsx')"""

df_baska_grouped = df_baska.groupby('TEAM').agg({'VALUE':'sum'}).sort_values('VALUE',ascending=False).reset_index()
df_yarali_grouped = df_yarali.groupby('TEAM').agg({'VALUE':'sum'}).sort_values('VALUE',ascending=False).reset_index()
df_asilsız_grouped = df_asilsız.groupby('TEAM').agg({'VALUE':'sum'}).sort_values('VALUE',ascending=False).reset_index()

df_baska_team_grouped= df_baska.groupby(['TEAM', 'Ekip No']).agg({'VALUE':'sum'}).sort_values('VALUE',ascending=False).reset_index()
df_yarali_team_grouped= df_yarali.groupby(['TEAM', 'Ekip No']).agg({'VALUE':'sum'}).sort_values('VALUE',ascending=False).reset_index()
df_asilsız_team_grouped= df_asilsız.groupby(['TEAM', 'Ekip No']).agg({'VALUE':'sum'}).sort_values('VALUE',ascending=False).reset_index()

df['TEAM']= df['Ekipteki Kişiler'].str.split(',')

df= df.explode('TEAM')

df= df[~(df['TEAM'].str.contains('Sürücü'))]

df['TEAM']= df['TEAM'].apply(lambda x: x.split(' - ')[0])

df['TEAM']= df['TEAM'].str.strip()

df['VALUE']= 1

df.groupby('TEAM').agg({'VALUE':'sum'}).sort_values('VALUE',ascending=False).reset_index().to_excel('C:/Users/mkaya/OneDrive/Masaüstü/BASKAARAC-YARALIYOK-ASILSIZIHBAR.xlsx')

df_grouped = df.groupby('TEAM').agg({'VALUE':'sum'}).sort_values('VALUE',ascending=False).reset_index()

df_grouped

df_team_grouped= df.groupby(['TEAM', 'Ekip No']).agg({'VALUE':'sum'}).sort_values('VALUE',ascending=False).reset_index()

pd.merge(df_grouped,df_team_grouped,on='TEAM').rename(columns={'VALUE_x':'TOPLAM BASKA ARAC-ASILSIZ-YARALI YOK','VALUE_y':'EKİPTEKİ TOPLAM'}).to_excel('C:/Users/mkaya/OneDrive/Masaüstü/BASKAARAC-YARALIYOK-ASILSIZIHBAR-EKIPTEKITOPLAM.xlsx')

df_team_grouped

pd.merge(df_baska_team_grouped,df_baska_grouped,on='TEAM').rename(columns={'VALUE_x':'TOPLAM BASKA ARAC','VALUE_y':'EKİPTEKİ TOPLAM'}).to_excel('C:/Users/mkaya/OneDrive/Masaüstü/BASKAARAC.xlsx')
pd.merge(df_yarali_team_grouped,df_yarali_grouped,on='TEAM').rename(columns={'VALUE_x':'TOPLAM YARALI YOK','VALUE_y':'EKİPTEKİ TOPLAM'}).to_excel('C:/Users/mkaya/OneDrive/Masaüstü/YARALI.xlsx')
pd.merge(df_asilsız_team_grouped,df_asilsız_grouped,on='TEAM').rename(columns={'VALUE_x':'TOPLAM ASILSIZ','VALUE_y':'EKİPTEKİ TOPLAM'}).to_excel('C:/Users/mkaya/OneDrive/Masaüstü/ASILSIZ.xlsx')

